# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Transaction_management.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 512)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 411, 191))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(10, 160, 241, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 160, 141, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.listWidget = QtWidgets.QListWidget(self.groupBox)
        self.listWidget.setGeometry(QtCore.QRect(10, 20, 391, 91))
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_2.setGeometry(QtCore.QRect(30, 120, 371, 31))
        self.listWidget_2.setObjectName("listWidget_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 21, 21))
        self.label_4.setObjectName("label_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 190, 411, 281))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(210, 110, 131, 21))
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setAutoRepeat(False)
        self.pushButton_4.setAutoExclusive(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(340, 110, 61, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.listWidget_3 = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget_3.setGeometry(QtCore.QRect(10, 20, 191, 251))
        self.listWidget_3.setObjectName("listWidget_3")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(230, 20, 171, 22))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(210, 20, 21, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(210, 50, 21, 16))
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(230, 50, 171, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(220, 80, 131, 21))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(330, 80, 71, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(420, 0, 351, 471))
        self.groupBox_4.setObjectName("groupBox_4")
        self.listWidget_6 = QtWidgets.QListWidget(self.groupBox_4)
        self.listWidget_6.setGeometry(QtCore.QRect(10, 240, 331, 181))
        self.listWidget_6.setObjectName("listWidget_6")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 430, 331, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.listWidget_5 = QtWidgets.QListWidget(self.groupBox_4)
        self.listWidget_5.setGeometry(QtCore.QRect(10, 20, 331, 211))
        self.listWidget_5.setObjectName("listWidget_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Пользователи"))
        self.pushButton.setText(_translate("MainWindow", "Добавить пользователя"))
        self.pushButton_2.setText(_translate("MainWindow", "Удалить"))
        self.label_4.setText(_translate("MainWindow", "ID="))
        self.groupBox_2.setTitle(_translate("MainWindow", "Список транзакций"))
        self.pushButton_4.setText(_translate("MainWindow", "Добавить транзакцию"))
        self.pushButton_3.setText(_translate("MainWindow", "Удалить"))
        self.label.setText(_translate("MainWindow", "От"))
        self.label_2.setText(_translate("MainWindow", "К"))
        self.label_3.setText(_translate("MainWindow", "Количество валюты"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Блокчейн и майнинг"))
        self.pushButton_6.setText(_translate("MainWindow", "Создать блок"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
