# Generated by Django 4.0.6 on 2022-08-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('UserId', models.IntegerField()),
                ('CheckId', models.IntegerField()),
                ('ProductName', models.CharField(max_length=128)),
                ('ProductCost', models.IntegerField()),
                ('MerchantName', models.CharField(max_length=128)),
                ('MCC', models.IntegerField()),
            ],
        ),
    ]
